export const ROUTES = {
  HOME: '/',
  TRANSACTIONS: '/transactions',
  TRANSACTIONS_NEW: '/transactions/new',
  TRANSACTIONS_EDIT: '/transactions/:id/edit',
  SETTINGS: '/settings',
  CATEGORIES: '/categories',
  CATEGORIES_NEW: '/categories/new',
  REPORTS: '/reports',
  BUDGETS: '/budgets',
  BUDGETS_NEW: '/budgets/new',
  RECURRING_BILLS: '/recurring-bills',
  RECURRING_BILLS_NEW: '/recurring-bills/new',
  RECURRING_BILLS_EDIT: '/recurring-bills/:id/edit',
  LOANS: '/loans',
  LOANS_DETAIL: '/loans/:id',
  BACKUP: '/backup',
  EXPORT: '/export',
  WALLETS: '/wallets',
  WALLETS_NEW: '/wallets/new',
  MORE: '/more',
} as const;
