export const ROUTES = {
  HOME: '/',
  TRANSACTIONS: '/transactions',
  TRANSACTIONS_NEW: '/transactions/new',
  TRANSACTIONS_EDIT: '/transactions/:id/edit',
  SETTINGS: '/settings',
  CATEGORIES: '/settings/categories',
  REPORTS: '/reports',
  BUDGETS: '/budgets',
  RECURRING_BILLS: '/recurring-bills',
  RECURRING_BILLS_NEW: '/recurring-bills/new',
  RECURRING_BILLS_EDIT: '/recurring-bills/:id/edit',
  BACKUP: '/backup',
  EXPORT: '/export',
  WALLETS: '/wallets',
  MORE: '/more',
} as const;
